In [41]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/blood-press/data.csv


We will be doing Hypothesis testing on this dataset

In [42]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [43]:
data = pd.read_csv("/kaggle/input/blood-press/data.csv")

In [44]:
data.head()

Patient_Number  Blood_Pressure_Abnormality  Level_of_Hemoglobin  \
0               1                           1                11.28   
1               2                           0                 9.75   
2               3                           1                10.79   
3               4                           0                11.00   
4               5                           1                14.17   

   Genetic_Pedigree_Coefficient  Age  BMI  Sex  Pregnancy  Smoking  \
0                          0.90   34   23    1        1.0        0   
1                          0.23   54   33    1        NaN        0   
2                          0.91   70   49    0        NaN        0   
3                          0.43   71   50    0        NaN        0   
4                          0.83   52   19    0        NaN        0   

   Physical_activity  salt_content_in_the_diet  alcohol_consumption_per_day  \
0              45961                     48071                          NaN   
1              26106                     25333                        205.0   
2               9995                     29465                         67.0   
3              10635                      7439                        242.0   
4              15619                     49644                        397.0   

   Level_of_Stress  Chronic_kidney_disease  Adrenal_and_thyroid_disorders  
0                2                       1                              1  
1                3                       0                              0  
2                2                       1                              0  
3                1                       1                              0  
4                2                       0                              0

In [45]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Patient_Number                 2000 non-null   int64  
 1   Blood_Pressure_Abnormality     2000 non-null   int64  
 2   Level_of_Hemoglobin            2000 non-null   float64
 3   Genetic_Pedigree_Coefficient   1908 non-null   float64
 4   Age                            2000 non-null   int64  
 5   BMI                            2000 non-null   int64  
 6   Sex                            2000 non-null   int64  
 7   Pregnancy                      442 non-null    float64
 8   Smoking                        2000 non-null   int64  
 9   Physical_activity              2000 non-null   int64  
 10  salt_content_in_the_diet       2000 non-null   int64  
 11  alcohol_consumption_per_day    1758 non-null   float64
 12  Level_of_Stress                2000 non-null   i

In [46]:
data.isnull().sum()

Patient_Number                      0
Blood_Pressure_Abnormality          0
Level_of_Hemoglobin                 0
Genetic_Pedigree_Coefficient       92
Age                                 0
BMI                                 0
Sex                                 0
Pregnancy                        1558
Smoking                             0
Physical_activity                   0
salt_content_in_the_diet            0
alcohol_consumption_per_day       242
Level_of_Stress                     0
Chronic_kidney_disease              0
Adrenal_and_thyroid_disorders       0
dtype: int64

In [47]:
data.drop(columns = ['Pregnancy','alcohol_consumption_per_day','Genetic_Pedigree_Coefficient'],axis=1,inplace=True)

CHECKING FOR NULL VALUES

In [48]:
data.isnull().sum()

Patient_Number                   0
Blood_Pressure_Abnormality       0
Level_of_Hemoglobin              0
Age                              0
BMI                              0
Sex                              0
Smoking                          0
Physical_activity                0
salt_content_in_the_diet         0
Level_of_Stress                  0
Chronic_kidney_disease           0
Adrenal_and_thyroid_disorders    0
dtype: int64

In [49]:
data['Level_of_Stress'].unique()

array([2, 3, 1])

In [50]:
data['Blood_Pressure_Abnormality'].unique()

array([1, 0])

In [51]:
dataset_table = pd.crosstab(data['Level_of_Stress'],data['Blood_Pressure_Abnormality'])
dataset_table

Blood_Pressure_Abnormality    0    1
Level_of_Stress                     
1                           339  327
2                           330  313
3                           344  347

> H0 :- Level_of_Strees and Blood_Pressure_Abnormality are related to each other


> H1 :- Level_of_Strees and Blood_Pressure_Abnormality are not related to each other

In [52]:
import scipy.stats as stats
Expected_val=stats.chi2_contingency(dataset_table)
Expected_val = Expected_val[3]

In [60]:
print(Expected_val)

[[337.329  328.671 ]
 [325.6795 317.3205]
 [349.9915 341.0085]]


In [53]:
no_of_rows=len(dataset_table.iloc[:,0])
print("no_of_rows :- ",no_of_rows)

no_of_columns=len(dataset_table.iloc[0,:])
print("no_of_columns :- ",no_of_columns)

ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05

no_of_rows :-  3
no_of_columns :-  2
Degree of Freedom:- 2


In [54]:
#Observed Values
Observed_Values = dataset_table.values 
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[339 327]
 [330 313]
 [344 347]]


In [55]:
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_val)])
chi_square_statistic=chi_square[0]+chi_square[1]
print(chi_square_statistic)

0.3407540821984837


In [56]:
alpha = 0.05 # Significance value

In [57]:
from scipy.stats import chi2
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 5.991464547107979


In [63]:
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('p-value:',p_value)

Significance level:  0.05
Degree of Freedom:  2
p-value: 0.8433467802466976


In [62]:
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between 2 categorical variables, ie: Level_of_Strees and Blood_Pressure_Abnormality are related to each other")
else:
    print("Retain H0,There is no relationship between 2 categorical variables, ie: Level_of_Strees and Blood_Pressure_Abnormality are not related to each other")
print(" ")
if p_value<=alpha:
    print("Reject H0,There is a relationship between 2 categorical variables, ie: Level_of_Strees and Blood_Pressure_Abnormality are related to each other")
else:
    print("Retain H0,There is no relationship between 2 categorical variables, ie: Level_of_Strees and Blood_Pressure_Abnormality are not related to each other")

Retain H0,There is no relationship between 2 categorical variables, ie: Level_of_Strees and Blood_Pressure_Abnormality are not related to each other
 
Retain H0,There is no relationship between 2 categorical variables, ie: Level_of_Strees and Blood_Pressure_Abnormality are not related to each other


This Statistical test declares that there is no relationship between level of stress and blood pressure levels. But we must remember that these test are based only on limited available data and may be wrong